name: Release Manager

on:
  push:
    tags:
      - 'v*'  # Workflow wyzwalany przez tagi w formacie vX.Y.Z

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Krok 1: Pobierz kod z tagu (nie z gałęzi main!)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}  # Checkout bezpośrednio z taga
          fetch-depth: 0

      # Krok 2: Ustaw wersję z nazwy taga
      - name: Set version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Krok 3: Aktualizuj manifest.json i commit do nowej gałęzi
      - name: Update version and push
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" custom_components/homeassistant_ai_support/manifest.json
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git checkout -b release-$VERSION
          git add custom_components/homeassistant_ai_support/manifest.json
          git commit -m "Update version to $VERSION"
          git push origin release-$VERSION

      # Krok 4: Utwórz release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: "v${{ env.VERSION }}"
          body: "Automatic version update"
