name: Release Manager

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Krok 1: Pobierz kod z gałęzi main
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      # Krok 2: Pobierz wersję z taga
      - name: Get version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Krok 3: Aktualizuj manifest.json
      - name: Update manifest version
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" custom_components/homeassistant_ai_support/manifest.json
          git add custom_components/homeassistant_ai_support/manifest.json
          git commit -m "Update version to $VERSION"
          git push origin main

      # Krok 4: Utwórz plik ZIP
      - name: Create ZIP archive
        run: |
          mkdir -p release
          cp -r custom_components/homeassistant_ai_support release/
          cd release
          zip -r homeassistant_ai_support.zip homeassistant_ai_support

      # Krok 5: Utwórz release i dodaj ZIP
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: "v${{ env.VERSION }}"
          body: "Automatyczna aktualizacja wersji"
          files: |
            release/homeassistant_ai_support.zip
