name: Release Manager

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Krok 1: Pobierz gałąź main
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      # Krok 2: Pobierz wersję z taga
      - name: Get version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Krok 3: Aktualizuj manifest.json i commit
      - name: Update manifest version
        run: |
          # Aktualizuj wersję w pliku
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" custom_components/homeassistant_ai_support/manifest.json
          
          # Konfiguracja Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Commit i push
          git add custom_components/homeassistant_ai_support/manifest.json
          git commit -m "Update version to $VERSION"
          git push origin main

      # Krok 4: Tworzenie pliku ZIP
      - name: Create ZIP file
        run: |
          mkdir -p release
          cd custom_components
          zip -r ../release/homeassistant_ai_support.zip homeassistant_ai_support

      # Krok 5: Utwórz release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: "v${{ env.VERSION }}"
          body: "Automatic version update"
          files: |
            release/homeassistant_ai_support.zip
