name: Release Manager

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Krok 1: Pobierz kod z gałęzi main
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      # Krok 2: Aktualizuj wersję w manifest.json
      - name: Update version
        run: |
          # Aktualizuj wersję w pliku
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" custom_components/homeassistant_ai_support/manifest.json

          # Konfiguracja Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add custom_components/homeassistant_ai_support/manifest.json
          git commit -m "Update version to $VERSION"
          git push origin main

      # Krok 3: Utwórz release z domyślnymi archiwami GitHub
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: "v${GITHUB_REF#refs/tags/v}"
          body: "Automatic version update"
