name: Create Release ZIP

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Wymagane do commitowania i pushowania zmian

    steps:
      # Krok 1: Pobranie kodu z pełną historią
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Pobierz pełną historię commitów

      # Krok 2: Ustawienie wersji z taga
      - name: Set version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # Krok 3: Aktualizacja manifest.json i commit zmian
      - name: Update and commit manifest
        run: |
          # Aktualizuj manifest.json
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" custom_components/homeassistant_ai_support/manifest.json
          
          # Konfiguracja git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Commit i push
          git add custom_components/homeassistant_ai_support/manifest.json
          git commit -m "Update version to $VERSION [skip ci]"
          git push origin main

      # Krok 4: Tworzenie pliku ZIP
      - name: Create ZIP file
        run: |
          mkdir -p release
          cp -r custom_components/homeassistant_ai_support release/
          cd release
          zip -r homeassistant_ai_support.zip homeassistant_ai_support

      # Krok 5: Upload pliku ZIP do Release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release/homeassistant_ai_support.zip
          asset_name: homeassistant_ai_support.zip
          asset_content_type: application/zip
